version: '3'
services:
  scheduler:
    build:
      context: ./scheduler
    ports:
      - "5000:80"
    tty: true
    volumes:
      - "./scheduler:/app"
      - "/var/run/docker.sock:/var/run/docker.sock"
  redis:
    image: "redis:alpine"
