version: '3'
services:
  scheduler:
    build:
      context: ./app
    ports:
      - "1024:5000"
    privileged: true
    stdin_open: true
    userns_mode: "keep-id"
    pid: "host"
    tty: true
    volumes:
      - /run/user/${UID}:/run/user/0:rshared # hosts the podman.sock
    networks:
      - default

  redis:
    image: "redis:alpine"
    # https://github.com/docker-library/redis/issues/35
    sysctls:
      - net.core.somaxconn=511
    networks:
      - default

networks:
  default:
    driver: bridge

# CONFIG on host:
# sudo nano /etc/subgid
# => add app_user
# sudo nano /etc/subuid
# => add app_user
 
# podman --url=unix:///run/user/501/podman/podman.sock ps