version: '3'
services:
  app:
    build:
      context: ./app
    ports:
      - "5000:80"
    tty: true
    links:
      - "scheduler:scheduler"
    volumes:
      - "./app:/app"
  scheduler:
    build:
      context: ./scheduler
    ports:
      - "4000:80"
    tty: true
    volumes:
      - "./scheduler:/app"
      - "/var/run/docker.sock:/var/run/docker.sock"
  redis:
    image: "redis:alpine"
