services:
  scheduler:
    build:
      context: ./app
    image: grading_server_scheduler
    ports:
      - "8080:5000"
    privileged: true
    stdin_open: true
    pid: "host"
    tty: true
    volumes:
      - /run/user/${UID}:/run/user/0:rshared # hosts the podman.sock
    networks:
      - default
    restart: always
    secrets:
      - app_password
      - gh_auth

  redis:
    image: "redis:alpine"
    restart: always
    networks:
      - default

networks:
  default:
    driver: bridge

secrets:
  app_password:
    file: secrets/app_password.txt
  gh_auth:
    file: secrets/gh_auth.txt