version: '3'
services:
  scheduler:
    build:
      context: ./app
    ports:
      - "5000:5000"
    tty: true
    volumes:
      #- "./app:/app"
      - "/var/run/docker.sock:/var/run/docker.sock"
  redis:
    image: "redis:alpine"
    # https://github.com/docker-library/redis/issues/35
    sysctls:
      - net.core.somaxconn=511
