version: '3'
services:
  scheduler:
    build:
      context: ./app
    image: grading_server_scheduler
    ports:
      - "8080:5000"
    privileged: true
    stdin_open: true
    pid: "host"
    tty: true
    volumes:
      - /run/user/${UID}:/run/user/0:rshared # hosts the podman.sock
    networks:
      - default
    secrets:
      - app_password

  redis:
    image: "redis:alpine"
    networks:
      - default

networks:
  default:
    driver: bridge

secrets:
  app_password:
    file: secrets/app_password.txt

# CONFIG on host:
# sudo nano /etc/subgid
# => add app_user
# sudo nano /etc/subuid
# => add app_user

# podman --url=unix:///run/user/0/podman/podman.sock ps